version: "2"

services:
  mongodb:
    restart: always
    image: mongo:3.2.3
    volumes:
      - ./data:/data/db
      - ./backup:/backup
      - ./conf/mongodb_backup/leanote_install_data:/init_data

  server:
    environment:
      - SITE_URL="http://localhost:9000"
    depends_on:
      - mongodb
    restart: always
    build: ./leanote
    ports:
      - "9000:9000"
    volumes:
      - ./conf/app.conf:/usr/local/leanote/conf/app.conf

volumes:
  leanote_data:
